<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProgramstudiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $programstudi = [
            ['id' => 1, 'nama' => 'Konstruksi Gedung, Sanitasi dan Perawatan'],
            ['id' => 2, 'nama' => 'Konstruksi Jalan, Irigasi dan Jembatan '],
            ['id' => 3, 'nama' => 'Bisnis Konstruksi dan Properti '],
            ['id' => 4, 'nama' => 'Desain Pemodelan dan Informasi Bangunan '],
            ['id' => 5, 'nama' => 'Teknik Geomatika'],
            ['id' => 6, 'nama' => 'Informasi Geospasial'],
            ['id' => 7, 'nama' => 'Teknik Pembangkit Tenaga Listri'],
            ['id' => 8, 'nama' => 'Teknik Jaringan Tenaga Listrik'],
            ['id' => 9, 'nama' => 'Teknik Instalasi Tenaga Listrik '],
            ['id' => 10, 'nama' => 'Teknik Otomasi Industri '],
            ['id' => 11, 'nama' => 'Teknik Pendinginan dan Tata Udara '],
            ['id' => 12, 'nama' => 'Teknik Tenaga Listri'],
            ['id' => 13, 'nama' => 'Teknik Pemesinan '],
            ['id' => 14, 'nama' => 'Teknik Pengelasan'],
            ['id' => 15, 'nama' => 'Teknik Pengecoran Logam'],
            ['id' => 16, 'nama' => 'Teknik Mekanik Industri'],
            ['id' => 17, 'nama' => 'Teknik Perancangan dan Gambar Mesin'],
            ['id' => 18, 'nama' => 'Teknik Fabrikasi Logam dan Manufaktu'],
            ['id' => 19, 'nama' => 'Airframe Power Plant '],
            ['id' => 20, 'nama' => 'Aircraft Machining'],
            ['id' => 21, 'nama' => 'Aircraft Sheet Metal Forming'],
            ['id' => 22, 'nama' => 'Airframe Mechanic'],
            ['id' => 23, 'nama' => 'Aircraft Electricity'],
            ['id' => 24, 'nama' => 'Aviation Electronics'],
            ['id' => 25, 'nama' => 'Desain Grafika'],
            ['id' => 26, 'nama' => 'Produksi Grafika'],
            ['id' => 27, 'nama' => 'Teknik Instrumentasi Loga'],
            ['id' => 28, 'nama' => 'Instrumentasi dan Otomatisasi Proses'],
            ['id' => 29, 'nama' => 'Teknik Pengendalian Produksi '],
            ['id' => 30, 'nama' => 'Teknik Tata Kelola Logistik'],
            ['id' => 31, 'nama' => 'Teknik Pemintalan Serat Buatan '],
            ['id' => 32, 'nama' => 'Teknik Pembuatan Benang '],
            ['id' => 33, 'nama' => 'Teknik Pembuatan Kain '],
            ['id' => 34, 'nama' => 'Teknik Penyempurnaan Tekstil '],
            ['id' => 35, 'nama' => 'Analisis Pengujian Laboratorium '],
            ['id' => 36, 'nama' => 'Kimia Industri'],
            ['id' => 37, 'nama' => 'Kimia Analisis'],
            ['id' => 38, 'nama' => 'Kimia Tekstil'],
            ['id' => 39, 'nama' => 'Teknik Kendaraan Ringan Otomotif '],
            ['id' => 40, 'nama' => 'Teknik dan Bisnis Sepeda Motor'],
            ['id' => 41, 'nama' => 'Teknik Alat Berat'],
            ['id' => 42, 'nama' => 'Teknik Bodi Otomotif '],
            ['id' => 43, 'nama' => 'Teknik Ototronik '],
            ['id' => 44, 'nama' => 'Teknik dan Manajemen Perawatan Otomotif '],
            ['id' => 45, 'nama' => 'Otomotif Daya dan Konversi Energi'],
            ['id' => 46, 'nama' => 'Konstruksi Kapal Baja'],
            ['id' => 47, 'nama' => 'Konstruksi Kapal Non Baja'],
            ['id' => 48, 'nama' => 'Teknik Pemesinan Kapal'],
            ['id' => 49, 'nama' => 'Teknik Pengelasan Kapal '],
            ['id' => 50, 'nama' => 'Teknik Kelistrikan Kapal'],
            ['id' => 51, 'nama' => 'Desain dan Rancang Bangun Kapal'],
            ['id' => 52, 'nama' => 'Interior Kapal'],
            ['id' => 53, 'nama' => 'Teknik Audio Video'],
            ['id' => 54, 'nama' => 'Teknik Elektronika Industri'],
            ['id' => 55, 'nama' => 'Teknik Mekatronika'],
            ['id' => 56, 'nama' => 'Teknik Elektronika Daya dan Komunikasi '],
            ['id' => 57, 'nama' => 'Instrumentasi Medik '],
            ['id' => 58, 'nama' => 'Teknik Produksi Minyak dan Gas '],
            ['id' => 59, 'nama' => 'Teknik Pemboran Minyak dan Gas'],
            ['id' => 60, 'nama' => 'Teknik Pengolahan Minyak, Gas dan Petrokimia '],
            ['id' => 61, 'nama' => 'Geologi Pertambangan'],
            ['id' => 62, 'nama' => 'Teknik Energi Surya, Hidro, dan Angin'],
            ['id' => 63, 'nama' => 'Teknik Energi Biomassa '],
            ['id' => 64, 'nama' => 'Rekayasa Perangkat Lunak'],
            ['id' => 65, 'nama' => 'Teknik Komputer dan Jaringan '],
            ['id' => 66, 'nama' => 'Sistem Informatika, Jaringan dan Aplikasi'],
            ['id' => 67, 'nama' => 'Teknik Transmisi Telekomunikas'],
            ['id' => 68, 'nama' => 'Teknik Jaringan Akses Telekomunikasi'],
            ['id' => 69, 'nama' => 'Asisten Keperawatan '],
            ['id' => 70, 'nama' => 'Dental Asisten'],
            ['id' => 71, 'nama' => 'Teknologi Laboratorium Medik'],
            ['id' => 72, 'nama' => 'Farmasi Klinis dan Komunitas'],
            ['id' => 73, 'nama' => 'Farmasi Industri'],
            ['id' => 74, 'nama' => 'Social Care (Keperawatan Sosial) '],
            ['id' => 75, 'nama' => 'Caregiver'],
            ['id' => 76, 'nama' => 'Agribisnis Tanaman Pangan dan Hortikultura'],
            ['id' => 77, 'nama' => 'Agribisnis Tanaman Perkebunan '],
            ['id' => 78, 'nama' => 'Pemuliaan dan Perbenihan Tanaman '],
            ['id' => 79, 'nama' => 'Lanskap dan Pertamanan '],
            ['id' => 80, 'nama' => 'Produksi dan Pengelolaan Perkebunan '],
            ['id' => 81, 'nama' => 'Agribisnis Organik Ekologi'],
            ['id' => 82, 'nama' => 'Agribisnis Ternak Ruminansia'],
            ['id' => 83, 'nama' => 'Agribisnis Ternak Unggas'],
            ['id' => 84, 'nama' => 'Industri Peternakan '],
            ['id' => 85, 'nama' => 'Keperawatan Hewan '],
            ['id' => 86, 'nama' => 'Kesehatan dan Reproduksi Hewan'],
            ['id' => 87, 'nama' => 'Agribisnis Pengolahan Hasil Pertanian '],
            ['id' => 88, 'nama' => 'Pengawasan Mutu Hasil Pertanian '],
            ['id' => 89, 'nama' => 'Agroindustri'],
            ['id' => 90, 'nama' => 'Alat Mesin Pertanian'],
            ['id' => 91, 'nama' => 'Otomatisasi Pertanian '],
            ['id' => 92, 'nama' => 'Teknik Inventarisasi dan Pemetaan Hutan '],
            ['id' => 93, 'nama' => 'Teknik Konservasi Sumber Daya Alam'],
            ['id' => 94, 'nama' => 'Teknik Rehabilitasi dan Reklamasi Hutan'],
            ['id' => 95, 'nama' => 'Teknologi Produksi Hasil Hutan'],
            ['id' => 96, 'nama' => 'Nautika Kapal Penangkap Ikan'],
            ['id' => 97, 'nama' => 'Teknika Kapal Penangkap Ikan '],
            ['id' => 98, 'nama' => 'Nautika Kapal Niaga'],
            ['id' => 99, 'nama' => 'Teknika Kapal Niaga '],
            ['id' => 100, 'nama' => 'Agribisnis Perikanan Air Tawar '],
            ['id' => 101, 'nama' => 'Agribisnis Perikanan Air Payau dan Laut'],
            ['id' => 102, 'nama' => 'Agribisnis Ikan Hias '],
            ['id' => 103, 'nama' => 'Agribisnis Rumput Laut '],
            ['id' => 104, 'nama' => 'Industri Perikanan Laut '],
            ['id' => 105, 'nama' => 'Agribisnis Pengolahan Hasil Perikanan'],
            ['id' => 106, 'nama' => 'Bisnis Daring dan Pemasaran'],
            ['id' => 107, 'nama' => 'Otomatisasi dan Tata Kelola Perkantoran'],
            ['id' => 108, 'nama' => 'Akuntansi dan Keuangan Lembaga'],
            ['id' => 109, 'nama' => 'Perbankan dan Keuangan Mikro '],
            ['id' => 110, 'nama' => 'Perbankan Syariah '],
            ['id' => 111, 'nama' => 'Usaha Perjalanan Wisata'],
            ['id' => 112, 'nama' => 'Wisata Bahari dan Ekowisata'],
            ['id' => 113, 'nama' => 'Tata Boga'],
            ['id' => 114, 'nama' => 'Tata Kecantikan Kulit dan Rambut'],
            ['id' => 115, 'nama' => 'Spa dan Beauty Therapy '],
            ['id' => 116, 'nama' => 'Tata Busana'],
            ['id' => 117, 'nama' => 'Desain Fesyen'],
            ['id' => 118, 'nama' => 'Seni Lukis'],
            ['id' => 119, 'nama' => 'Seni Patung'],
            ['id' => 120, 'nama' => 'Desain Komunikasi Visual '],
            ['id' => 121, 'nama' => 'Desain Interior dan Teknik Furnitur '],
            ['id' => 122, 'nama' => 'Animasi'],
            ['id' => 123, 'nama' => 'Kriya Kreatif Batik dan Tekstil '],
            ['id' => 124, 'nama' => 'Kriya Kreatif Kulit dan Imitasi '],
            ['id' => 125, 'nama' => 'Kriya Kreatif Keramik '],
            ['id' => 126, 'nama' => 'Kriya Kreatif Logam dan Perhiasan '],
            ['id' => 127, 'nama' => 'Kriya Kreatif Kayu dan Rotan'],
            ['id' => 128, 'nama' => 'Seni Musik Klasik '],
            ['id' => 129, 'nama' => 'Seni Musik Populer '],
            ['id' => 130, 'nama' => 'Seni Tari'],
            ['id' => 131, 'nama' => 'Penataan Tari'],
            ['id' => 132, 'nama' => 'Seni Karawitan'],
            ['id' => 133, 'nama' => 'Penataan Karawitan '],
            ['id' => 134, 'nama' => 'Seni Pedalangan '],
            ['id' => 135, 'nama' => 'Pemeranan'],
            ['id' => 136, 'nama' => 'Tata Artistik Teater'],
            ['id' => 137, 'nama' => 'Produksi dan Siaran Program Radio'],
            ['id' => 138, 'nama' => 'Produksi dan Siaran Program Televisi '],
            ['id' => 139, 'nama' => 'Produksi Film dan Program Televisi'],
            ['id' => 140, 'nama' => 'Teknik Gambar Bangunan'],
            ['id' => 141, 'nama' => 'Multimedia'],
            ['id' => 142, 'nama' => 'SMA - IPA'],
            ['id' => 143, 'nama' => 'SMA - IPS'],
            ['id' => 144, 'nama' => 'Teknik Konstruksi Baja'],
            ['id' => 145, 'nama' => 'Teknik Konstruksi Kayu'],
            ['id' => 146, 'nama' => 'Teknik Konstruksi Batu dan Beton'],
            ['id' => 147, 'nama' => 'Teknik Furniture'],
            ['id' => 148, 'nama' => 'Teknik Plumbing dan Sanitasi'],
            ['id' => 149, 'nama' => 'Teknik Survei dan Pemetaan'],
            ['id' => 150, 'nama' => 'Teknik Pembangkit Tenaga Listrik'],
            ['id' => 151, 'nama' => 'Teknik Distribusi Tenaga Listrik'],
            ['id' => 152, 'nama' => 'Teknik Transmisi Tenaga Listrik'],
            ['id' => 153, 'nama' => 'Teknik Instalasi Tenaga Listrik'],
            ['id' => 154, 'nama' => 'Teknik Otomasi Industri'],
            ['id' => 155, 'nama' => 'Teknik Pendingan dan Tata Udara'],
            ['id' => 156, 'nama' => 'Teknik Pemesinan'],
            ['id' => 157, 'nama' => 'Teknik Fabrikasi Logam'],
            ['id' => 158, 'nama' => 'Teknik Gambar Mesin'],
            ['id' => 159, 'nama' => 'Teknik Pemeliharaan Mekanik Industri'],
            ['id' => 160, 'nama' => 'Teknik Kendaraan Ringan'],
            ['id' => 161, 'nama' => 'Teknik Sepeda Motor'],
            ['id' => 162, 'nama' => 'Teknik Perbaikan Bodi Otomotif'],
            ['id' => 163, 'nama' => 'Teknik Ototronik'],
            ['id' => 164, 'nama' => 'Air Frame dan Power Plant'],
            ['id' => 165, 'nama' => 'Pemesinan Pesawat Udara'],
            ['id' => 166, 'nama' => 'Konstruksi Badan Pesawat Udara'],
            ['id' => 167, 'nama' => 'Konstruksi Rangka Pesawat Udara'],
            ['id' => 168, 'nama' => 'Kelistrikan Pesawat Udara'],
            ['id' => 169, 'nama' => 'Elektronika Pesawat Udara'],
            ['id' => 170, 'nama' => 'Pemeliharaan dan Perbaikan Instrumen Elektronika'],
            ['id' => 171, 'nama' => 'Teknik Konstruksi Kapal Baja'],
            ['id' => 172, 'nama' => 'Teknik Konstruksi Kapal Kayu'],
            ['id' => 173, 'nama' => 'Teknik Konstruksi Kapa Fiberglas'],
            ['id' => 174, 'nama' => 'Teknik Instalasi Pemesinan Kapal'],
            ['id' => 175, 'nama' => 'Teknik Pengelasan Kapal'],
            ['id' => 176, 'nama' => 'Kelistrikan Kapal'],
            ['id' => 177, 'nama' => 'Teknik Gambar Rancang Bangun Kapal'],
            ['id' => 178, 'nama' => 'Teknik Pemintalan Serat Buatan'],
            ['id' => 179, 'nama' => 'Teknik Pembuatan Benang'],
            ['id' => 180, 'nama' => 'Teknik Pembuatan Kain'],
            ['id' => 181, 'nama' => 'Teknik Penyempuraan Tekstil'],
            ['id' => 182, 'nama' => 'Garmen'],
            ['id' => 183, 'nama' => 'Persiapan Grafika'],
            ['id' => 184, 'nama' => 'Teknik Instrumentasi Gelas'],
            ['id' => 185, 'nama' => 'Teknik Instrumentasi Logam'],
            ['id' => 186, 'nama' => 'Kontrol Proses'],
            ['id' => 187, 'nama' => 'Kontrok Mekanik'],
            ['id' => 188, 'nama' => 'Neutika Kapal Penangkap Ikan'],
            ['id' => 189, 'nama' => 'Teknika Kapal Penangkap Ikan'],
            ['id' => 190, 'nama' => 'Neutika Kapal Niaga'],
            ['id' => 191, 'nama' => 'Teknika Kapal Niaga'],
            ['id' => 192, 'nama' => 'Teknik dan Managemen Produksi'],
            ['id' => 193, 'nama' => 'Teknik dan Managemen Pergudangan'],
            ['id' => 194, 'nama' => 'Teknik dan Managemen Transportasi'],
            ['id' => 195, 'nama' => 'Teknik Produksi Perminyakan'],
            ['id' => 196, 'nama' => 'Teknik Pengeboran Minyak'],
            ['id' => 197, 'nama' => 'Teknik Pengolahan Mingak, Gas dan Petrokimia'],
            ['id' => 198, 'nama' => 'Tekniok Konstruksi Batu dan Beton'],
            ['id' => 199, 'nama' => 'Teknik Furnitur'],
            ['id' => 200, 'nama' => 'Teknik Plambing dan Sanitasi'],
            ['id' => 201, 'nama' => 'Geomatika'],
            ['id' => 202, 'nama' => 'Teknik Instalasi Pemanfaatan Tenaga Listrik'],
            ['id' => 203, 'nama' => 'Teknik Pendingin dan Tata Udara'],
            ['id' => 204, 'nama' => 'Pemeliharaan dan Perbaikan Motor dan Rangka Pesawat Udara ( Airframe Power Plant)'],
            ['id' => 205, 'nama' => 'Pemesinan Pesawat Udara ( Aircraft Machining)'],
            ['id' => 206, 'nama' => 'Konstruksi Badan Pesawat Udara ( Aircraft Sheet Metal Forming)'],
            ['id' => 207, 'nama' => 'Konstruksi Rangka Pesawat Udara ( Airframe Mechanics)'],
            ['id' => 208, 'nama' => 'Kelistrikan Pesawat Udara ( Aircraft Electricity)'],
            ['id' => 209, 'nama' => 'Elektronika Pesawat Udara ( Aviation Electronis )'],
            ['id' => 210, 'nama' => 'Pemeliharaan dan Perbaikan Instrumen Elektronika Pesawat Udara (Electrical Avionics )'],
            ['id' => 211, 'nama' => 'Kontrol Mekanik'],
            ['id' => 212, 'nama' => 'Teknik Pelayanan Produksi'],
            ['id' => 213, 'nama' => 'Teknik Pergudangan'],
            ['id' => 214, 'nama' => 'Teknik Penyempurnaan Tekstil'],
            ['id' => 215, 'nama' => 'Teknik Produksi Minyak dan Gas'],
            ['id' => 216, 'nama' => 'Teknik Pengolahan Minyak, Gas dan Petrokimia'],
            ['id' => 217, 'nama' => 'Teknik Konstruksi Kapal Fiberglass'],
            ['id' => 218, 'nama' => 'Teknik Elektronika Komunikasi'],
            ['id' => 219, 'nama' => 'Teknik Energi Hidro'],
            ['id' => 220, 'nama' => 'Teknik Energi Surya dan Angin'],
            ['id' => 221, 'nama' => 'Teknik Energi Biomassa'],
            ['id' => 222, 'nama' => 'Teknik Transmisi Telekomunikasi'],
            ['id' => 223, 'nama' => 'Teknik Suitsing'],
            ['id' => 224, 'nama' => 'Teknik Jaringan Akses'],
            ['id' => 225, 'nama' => 'Teknik Komputer dan Jaringan'],
            ['id' => 226, 'nama' => 'Teknik Produksi dan Penyiaran Program Pertelevisian'],
            ['id' => 227, 'nama' => 'Teknik Produlsi dan Penyiaran Program Radio'],
            ['id' => 228, 'nama' => 'Teknik Produksi dan Penyiaran Program Radio dan Pertelevisian'],
            ['id' => 229, 'nama' => 'Perawat Kesehatan'],
            ['id' => 230, 'nama' => 'Perawat Gigi'],
            ['id' => 231, 'nama' => 'Analis Kesehatan'],
            ['id' => 232, 'nama' => 'Farmasi'],
            ['id' => 233, 'nama' => 'Perawatan Sosial'],
            ['id' => 234, 'nama' => 'Keperawatan'],
            ['id' => 235, 'nama' => 'Keperawatan Gigi'],
            ['id' => 236, 'nama' => 'Pekerjaan Sosial'],
            ['id' => 237, 'nama' => 'Agribisnis Tanaman Perkebunan'],
            ['id' => 238, 'nama' => 'Agribisnis Pembibitan dan Kultur Jaringan Tanaman'],
            ['id' => 239, 'nama' => 'Agribisnis Aneka Ternak'],
            ['id' => 240, 'nama' => 'Perawatan Kesehatan Ternak'],
            ['id' => 241, 'nama' => 'Agribisnis Perikanan'],
            ['id' => 242, 'nama' => 'Agribisnis Rumput Laut'],
            ['id' => 243, 'nama' => 'Mekanisasi Pertanian'],
            ['id' => 244, 'nama' => 'Teknologi Pengolahan Hasil Pertanian'],
            ['id' => 245, 'nama' => 'Pengawasan Mutu'],
            ['id' => 246, 'nama' => 'Kehutanan'],
            ['id' => 247, 'nama' => 'Agribisnis Perbenihan dan Kultur Jaringan Tanaman'],
            ['id' => 248, 'nama' => 'Kesehatan Hewan'],
            ['id' => 249, 'nama' => 'Teknologi Pengolahan Hasil Perikanan'],
            ['id' => 250, 'nama' => 'Pengawasan Mutu Hasil Pertanian dan Perikanan'],
            ['id' => 251, 'nama' => 'Teknik Tanah dan Air'],
            ['id' => 252, 'nama' => 'Teknik Inventarisasi dan Pemetaan Hutan'],
            ['id' => 253, 'nama' => 'Teknik Konservasi Sumberdaya Hutan'],
            ['id' => 254, 'nama' => 'Teknik Produksi Hasil Hutan'],
            ['id' => 255, 'nama' => 'Administrasi Perkantoran'],
            ['id' => 256, 'nama' => 'Akuntansi'],
            ['id' => 257, 'nama' => 'Perbankan'],
            ['id' => 258, 'nama' => 'Pemasaran'],
            ['id' => 259, 'nama' => 'Perbankan Syariah'],
            ['id' => 260, 'nama' => 'Budidaya Perikanan'],
            ['id' => 261, 'nama' => 'Budidaya Krustacea'],
            ['id' => 262, 'nama' => 'Budidaya Kekerangan'],
            ['id' => 263, 'nama' => 'Budidaya Rumput Laut'],
            ['id' => 264, 'nama' => 'Akomodasi Perhotelan'],
            ['id' => 265, 'nama' => 'Jasa Boga'],
            ['id' => 266, 'nama' => 'Patiseri'],
            ['id' => 267, 'nama' => 'Kecantikan Kulit'],
            ['id' => 268, 'nama' => 'Kecantikan Rambut'],
            ['id' => 269, 'nama' => 'Busana Butik'],
            ['id' => 270, 'nama' => 'Tata Kecantikan Rambut'],
            ['id' => 271, 'nama' => 'Tata Kecantikan Kulit'],
            ['id' => 272, 'nama' => 'Desain Komunikasi Visual'],
            ['id' => 273, 'nama' => 'Desain Produksi Interior dan Landscaping'],
            ['id' => 274, 'nama' => 'Desain dan Produksi Kria Tekstil'],
            ['id' => 275, 'nama' => 'Desain dan Produksi Kria Kulit'],
            ['id' => 276, 'nama' => 'Desain dan Produksi Kria Keramik'],
            ['id' => 277, 'nama' => 'Desain dan Produksi Kria Logam'],
            ['id' => 278, 'nama' => 'Desain dan Produksi Kria Kayu'],
            ['id' => 279, 'nama' => 'Seni Musik Klasik'],
            ['id' => 280, 'nama' => 'Seni Musik Non Klasik'],
            ['id' => 281, 'nama' => 'Seni Kerawitan'],
            ['id' => 282, 'nama' => 'Seni Pedalangan'],
            ['id' => 283, 'nama' => 'Seni Teater'],
            ['id' => 284, 'nama' => 'Desain Interior'],
            ['id' => 285, 'nama' => 'Desain dan Produksi Kriya Tekstil'],
            ['id' => 286, 'nama' => 'Desain dan Produksi Kriya Kulit'],
            ['id' => 287, 'nama' => 'Desain dan Produksi Kriya Keramik'],
            ['id' => 288, 'nama' => 'Desain dan Produksi Kriya Logam'],
            ['id' => 289, 'nama' => 'Desain dan Produksi Kriya Kayu'],
            ['id' => 290, 'nama' => 'Tata Artistik'],
            ['id' => 291, 'nama' => 'Pendidikan Islam'],
            ['id' => 292, 'nama' => 'Teknik Konstruksi Batu Beton (TKBB)'],
            ['id' => 293, 'nama' => 'Kedokteran'],
            ['id' => 294, 'nama' => 'Kedokteran Gigi'],
            ['id' => 295, 'nama' => 'Kedokteran Hewan'],
            ['id' => 296, 'nama' => 'Kesehatan Masyarakat'],
            ['id' => 297, 'nama' => 'Kesehatan Lingkungan'],
            ['id' => 298, 'nama' => 'Ilmu Gizi'],
            ['id' => 299, 'nama' => 'Keselamatan &amp; Kesehatan Kerja'],
            ['id' => 300, 'nama' => 'Ilmu Keperawatan'],
            ['id' => 301, 'nama' => 'Nutrisi dan Teknologi Pangan'],
            ['id' => 302, 'nama' => 'Kebidanan'],
            ['id' => 303, 'nama' => 'Fisioterafi'],
            ['id' => 304, 'nama' => 'Ilmu Keolahragaan'],
            ['id' => 305, 'nama' => 'Teknik Radiodiagnostik dan Radioterapi'],
            ['id' => 306, 'nama' => 'Manajemen Pelayanan Rumah Sakit'],
            ['id' => 307, 'nama' => 'Matematika'],
            ['id' => 308, 'nama' => 'Fisika'],
            ['id' => 309, 'nama' => 'Kimia'],
            ['id' => 310, 'nama' => 'Biologi'],
            ['id' => 311, 'nama' => 'Statistika'],
            ['id' => 312, 'nama' => 'Astronomi'],
            ['id' => 313, 'nama' => 'Bioteknologi'],
            ['id' => 314, 'nama' => 'Geofisika'],
            ['id' => 315, 'nama' => 'Meteorologi'],
            ['id' => 316, 'nama' => 'Geografi'],
            ['id' => 317, 'nama' => 'Biokimia'],
            ['id' => 318, 'nama' => 'Metrologi'],
            ['id' => 319, 'nama' => 'Aktuaria'],
            ['id' => 320, 'nama' => 'Statistika Terapan'],
            ['id' => 321, 'nama' => 'Mikrobiologi'],
            ['id' => 322, 'nama' => 'Bioentrepreneurship'],
            ['id' => 323, 'nama' => 'Ilmu Pangan (Food Science)'],
            ['id' => 324, 'nama' => 'Matematika Bisnis'],
            ['id' => 325, 'nama' => 'Fisika Medis'],
            ['id' => 326, 'nama' => 'Kartografi dan Penginderaan Jauh'],
            ['id' => 327, 'nama' => 'Pengelolaan dan Pemberdayaan SDA dan Lingkungan'],
            ['id' => 328, 'nama' => 'Sosial dan Humaniora'],
            ['id' => 329, 'nama' => 'llmu Politik'],
            ['id' => 330, 'nama' => 'Filsafat'],
            ['id' => 331, 'nama' => 'Kriminologi'],
            ['id' => 332, 'nama' => 'Psikologi'],
            ['id' => 333, 'nama' => 'Ilmu Hukum'],
            ['id' => 334, 'nama' => 'Sosiologi'],
            ['id' => 335, 'nama' => 'Jurnalistik'],
            ['id' => 336, 'nama' => 'Antropologi'],
            ['id' => 337, 'nama' => 'Hubungan Internasional (HI)'],
            ['id' => 338, 'nama' => 'Ilmu Kesejahteraan Sosial'],
            ['id' => 339, 'nama' => 'Ilmu Pemerintahan'],
            ['id' => 340, 'nama' => 'Administrasi Publik'],
            ['id' => 341, 'nama' => 'Administrasi Bisnis'],
            ['id' => 342, 'nama' => 'Ilmu Komunikasi'],
            ['id' => 343, 'nama' => 'Hubungan Masyarakat'],
            ['id' => 344, 'nama' => 'Marketing Communication'],
            ['id' => 345, 'nama' => 'Penyiaran (Broadcasting)'],
            ['id' => 346, 'nama' => 'Periklanan (Advertiing)'],
            ['id' => 347, 'nama' => 'Peradilan Agama'],
            ['id' => 348, 'nama' => 'Politik Islam'],
            ['id' => 349, 'nama' => 'Pembangunan Sosial dan Kesejahteraan'],
            ['id' => 350, 'nama' => 'Business Law'],
            ['id' => 351, 'nama' => 'Manajemen Komunikasi'],
            ['id' => 352, 'nama' => 'Branding'],
            ['id' => 353, 'nama' => 'Kearsipan'],
            ['id' => 354, 'nama' => 'Sains Komunikasi dan Pengembangan Masyarakat'],
            ['id' => 355, 'nama' => 'Ilmu Keluarga dan Konsumen'],
            ['id' => 356, 'nama' => 'Manajemen Produksi Media'],
            ['id' => 357, 'nama' => 'Ekonomi dan Bisnis '],
            ['id' => 358, 'nama' => 'Manajemen Keuangan'],
            ['id' => 359, 'nama' => 'Menajemen Sumber Daya Manusia dan Organisasi'],
            ['id' => 360, 'nama' => 'Manajemen Operasi'],
            ['id' => 361, 'nama' => 'Manajemen Pemasaran'],
            ['id' => 362, 'nama' => 'Administrasi Fiskal'],
            ['id' => 363, 'nama' => 'Ekonomi'],
            ['id' => 364, 'nama' => 'Bisnis Internasional'],
            ['id' => 365, 'nama' => 'Manajemen Informatika'],
            ['id' => 366, 'nama' => 'Ekonomi Pembangunan'],
            ['id' => 367, 'nama' => 'Techopreneurship'],
            ['id' => 368, 'nama' => 'Green Economy'],
            ['id' => 369, 'nama' => 'Manajemen Bisnis'],
            ['id' => 370, 'nama' => 'Administrasi Niaga'],
            ['id' => 371, 'nama' => 'Manajemen Keuangan Syariah'],
            ['id' => 372, 'nama' => 'Bisnis Islam'],
            ['id' => 373, 'nama' => 'Business Creation'],
            ['id' => 374, 'nama' => 'Kewirausahaan'],
            ['id' => 375, 'nama' => 'Manajemen Bisnis dan Pemasaran'],
            ['id' => 376, 'nama' => 'Manajemen Bisnis Internasional'],
            ['id' => 377, 'nama' => 'Ekonomi Syariah'],
            ['id' => 378, 'nama' => 'Keuangan'],
            ['id' => 379, 'nama' => 'Pemasaran Internasional'],
            ['id' => 380, 'nama' => 'Ekonomi Bisnis'],
            ['id' => 381, 'nama' => 'Akuntansi Bisnis'],
            ['id' => 382, 'nama' => 'Manajemen Pariwisata'],
            ['id' => 383, 'nama' => 'Manajemen'],
            ['id' => 384, 'nama' => 'Manajemen Transportasi'],
            ['id' => 385, 'nama' => 'Akuntansi Sektor Publik'],
            ['id' => 386, 'nama' => 'Manajemen Industri Katering'],
            ['id' => 387, 'nama' => 'Administrasi Keuangan'],
            ['id' => 388, 'nama' => 'Manajemen Bisnis Telekomunikasi Informatika'],
            ['id' => 389, 'nama' => 'Sastra dan Budaya '],
            ['id' => 390, 'nama' => 'Sastra Inggris'],
            ['id' => 391, 'nama' => 'Arkeologi'],
            ['id' => 392, 'nama' => 'Sastra Jawa'],
            ['id' => 393, 'nama' => 'Sastra Arab'],
            ['id' => 394, 'nama' => 'Sastra Jepang'],
            ['id' => 395, 'nama' => 'Sastra Indonesia'],
            ['id' => 396, 'nama' => 'Sastra Rusia'],
            ['id' => 397, 'nama' => 'Sastra Perancis'],
            ['id' => 398, 'nama' => 'Sastra Korea'],
            ['id' => 399, 'nama' => 'Sastra Jerman'],
            ['id' => 400, 'nama' => 'Sastra Belanda'],
            ['id' => 401, 'nama' => 'Sastra Cina'],
            ['id' => 402, 'nama' => 'Sastra Sunda'],
            ['id' => 403, 'nama' => 'Sastra Bali'],
            ['id' => 404, 'nama' => 'Sastra Slavia'],
            ['id' => 405, 'nama' => 'Sastra Minangkabau'],
            ['id' => 406, 'nama' => 'Sastra Nusantara'],
            ['id' => 407, 'nama' => 'Sejarah dan Kebudayaan Islam'],
            ['id' => 408, 'nama' => 'Komputer dan Teknologi '],
            ['id' => 409, 'nama' => 'Mobile Application &amp; Technology'],
            ['id' => 410, 'nama' => 'Sistem Informasi (Manajemen Informatika)'],
            ['id' => 411, 'nama' => 'Teknologi Game'],
            ['id' => 412, 'nama' => 'Ilmu Komputasi'],
            ['id' => 413, 'nama' => 'Cyber Security'],
            ['id' => 414, 'nama' => 'Bioinformatika'],
            ['id' => 415, 'nama' => 'Sistem Komputer (Teknik Komputer)'],
            ['id' => 416, 'nama' => 'Sistem Informasi Bisnis'],
            ['id' => 417, 'nama' => 'Software Engineering'],
            ['id' => 418, 'nama' => 'Sistem dan Teknologi Informasi'],
            ['id' => 419, 'nama' => 'Computerized Accounting'],
            ['id' => 420, 'nama' => 'Information Systems Audit'],
            ['id' => 421, 'nama' => 'Accounting Information'],
            ['id' => 422, 'nama' => 'Audio Engineering'],
            ['id' => 423, 'nama' => 'Ilmu Komputer'],
            ['id' => 424, 'nama' => 'Human Computer Interaction'],
            ['id' => 425, 'nama' => 'Pendidikan '],
            ['id' => 426, 'nama' => 'Manajemen Pendidikan'],
            ['id' => 427, 'nama' => 'Kurikulum dan Teknologi Pendidikan'],
            ['id' => 428, 'nama' => 'Pendidikan Luar Sekolah'],
            ['id' => 429, 'nama' => 'Pendidikan Luar Biasa (PLB)'],
            ['id' => 430, 'nama' => 'Pendidikan Anak Usia Dini (PAUD)'],
            ['id' => 431, 'nama' => 'Administrasi Pendidikan'],
            ['id' => 432, 'nama' => 'Pendidikan Bimbingan Konseling'],
            ['id' => 433, 'nama' => 'Ilmu Perpustakaan'],
            ['id' => 434, 'nama' => 'Teologi'],
            ['id' => 435, 'nama' => 'Pendidikan Kependudukan'],
            ['id' => 436, 'nama' => 'Tafsir Hadits'],
            ['id' => 437, 'nama' => 'Pendidikan Pancasila dan Kewarganegaraan'],
            ['id' => 438, 'nama' => 'Pendidikan Agama Islam'],
            ['id' => 439, 'nama' => 'Pendidikan Kepelatihan Olahraga'],
            ['id' => 440, 'nama' => 'Pendidikan Jasmani Kesehatan dan Rekreasi'],
            ['id' => 441, 'nama' => 'Pendidikan Ilmu Pengetahuan Alam'],
            ['id' => 442, 'nama' => 'Pendidikan Bahasa Inggris'],
            ['id' => 443, 'nama' => 'Pendidikan Bahasa dan Sastra Indonesia'],
            ['id' => 444, 'nama' => 'Pendidikan Sejarah'],
            ['id' => 445, 'nama' => 'Pendidikan Matematika'],
            ['id' => 446, 'nama' => 'Manajemen Pendidikan Islam'],
            ['id' => 447, 'nama' => 'Pendidikan Geografi'],
            ['id' => 448, 'nama' => 'Pendidikan Bahasa Arab'],
            ['id' => 449, 'nama' => 'Pertanian '],
            ['id' => 450, 'nama' => 'Mikrobiologi Pertanian'],
            ['id' => 451, 'nama' => 'Agribisnis (Sosial Ekonomi Pertanian)'],
            ['id' => 452, 'nama' => 'Agroteknologi'],
            ['id' => 453, 'nama' => 'Ilmu Kelautan'],
            ['id' => 454, 'nama' => 'Peternakan'],
            ['id' => 455, 'nama' => 'Agroeteknologi'],
            ['id' => 456, 'nama' => 'Budidaya Perairan (Akuakultur)'],
            ['id' => 457, 'nama' => 'Teknologi Pangan'],
            ['id' => 458, 'nama' => 'Rekayasa Pertanian'],
            ['id' => 459, 'nama' => 'Teknologi Pasca Panen'],
            ['id' => 460, 'nama' => 'Teknologi Hasil Hutan'],
            ['id' => 461, 'nama' => 'Silvikulutur'],
            ['id' => 462, 'nama' => 'Konservasi Sumberdaya Hutan dan Ekowisata'],
            ['id' => 463, 'nama' => 'Ilmu Hama dan Penyakit Tumbuhan (Proteksi Tanaman)'],
            ['id' => 464, 'nama' => 'Teknologi Industri Pertanian (Agroindustri)'],
            ['id' => 465, 'nama' => 'Manajemen Sumberdaya Lahan (Ilmu Tanah)'],
            ['id' => 466, 'nama' => 'Teknologi Hasil Perikanan'],
            ['id' => 467, 'nama' => 'Agrobisnis Perikanan (Sosial Ekonomi Perikanan)'],
            ['id' => 468, 'nama' => 'Pengelolaan Hutan'],
            ['id' => 469, 'nama' => 'Pemanfaatan Sumberdaya Perikanan'],
            ['id' => 470, 'nama' => 'Teknologi Industri Benih'],
            ['id' => 471, 'nama' => 'Produksi Ternak'],
            ['id' => 472, 'nama' => 'Teknologi Hasil Ternak'],
            ['id' => 473, 'nama' => 'Manajemen Sumber Daya Perairan'],
            ['id' => 474, 'nama' => 'Manajemen Hutan'],
            ['id' => 475, 'nama' => 'Penyuluhan dan Komunikasi Pertanian'],
            ['id' => 476, 'nama' => 'Teknik Pertanian'],
            ['id' => 477, 'nama' => 'Manajemen Bisnis Unggas'],
            ['id' => 478, 'nama' => 'Profesi dan Ilmu Terapan '],
            ['id' => 479, 'nama' => 'Pendidikan Kepolisian'],
            ['id' => 480, 'nama' => 'Pendidikan Militer'],
            ['id' => 481, 'nama' => 'Penerbang (Pendidikan Pilot)'],
            ['id' => 482, 'nama' => 'Pendidikan Intelijen'],
            ['id' => 483, 'nama' => 'Komunikasi Penerbangan'],
            ['id' => 484, 'nama' => 'Lalu Lintas Udara'],
            ['id' => 485, 'nama' => 'Manajemen Logistik'],
            ['id' => 486, 'nama' => 'Seni '],
            ['id' => 487, 'nama' => 'Desain Produk'],
            ['id' => 488, 'nama' => 'Furniture Design'],
            ['id' => 489, 'nama' => 'Desain Grafis'],
            ['id' => 490, 'nama' => 'DKV New Media'],
            ['id' => 491, 'nama' => 'DKV Creative Advertising'],
            ['id' => 492, 'nama' => 'Teknik '],
            ['id' => 493, 'nama' => 'Teknik Kelautan'],
            ['id' => 494, 'nama' => 'Teknik Lingkungan'],
            ['id' => 495, 'nama' => 'Teknik Metalurgi'],
            ['id' => 496, 'nama' => 'Teknik Sipil'],
            ['id' => 497, 'nama' => 'Arsitektur'],
            ['id' => 498, 'nama' => 'Teknik Geodesi'],
            ['id' => 499, 'nama' => 'Teknik Elektro'],
            ['id' => 500, 'nama' => 'Teknik Mesin'],
            ['id' => 501, 'nama' => 'Teknik Industri'],
            ['id' => 502, 'nama' => 'Teknik Perkapalan'],
            ['id' => 503, 'nama' => 'Teknik Perencanaan Wilayah dan Kota (Planologi)'],
            ['id' => 504, 'nama' => 'Teknik Penerbangan (Aeronautika dan Astronautika)'],
            ['id' => 505, 'nama' => 'Oseanografi'],
            ['id' => 506, 'nama' => 'Teknik Nuklir'],
            ['id' => 507, 'nama' => 'Teknik Geologi'],
            ['id' => 508, 'nama' => 'Teknik Otomotif'],
            ['id' => 509, 'nama' => 'Teknobiomedik'],
            ['id' => 510, 'nama' => 'Teknik Perancangan Jalan dan Jembatan'],
            ['id' => 511, 'nama' => 'Teknik Refrigerasi dan Tata Udara'],
            ['id' => 512, 'nama' => 'Teknik Telekomunikasi'],
            ['id' => 513, 'nama' => 'Teknologi Bioproses'],
            ['id' => 514, 'nama' => 'Teknik Grafika'],
            ['id' => 515, 'nama' => 'Transportasi Laut'],
            ['id' => 516, 'nama' => 'Teknik Otomasi Manufaktur dan Mekatronika'],
            ['id' => 517, 'nama' => 'Rekayasa hayati'],
            ['id' => 518, 'nama' => 'Teknik Material'],
            ['id' => 519, 'nama' => 'Automotive and Robotics Engineering'],
            ['id' => 520, 'nama' => 'Teknik Tenaga Listrik'],
            ['id' => 521, 'nama' => 'Teknik Sistem Komputer'],
            ['id' => 522, 'nama' => 'Manajemen Rekayasa Industri'],
            ['id' => 523, 'nama' => 'Teknik Bioenergi dan Kemurgi'],
            ['id' => 524, 'nama' => 'Industrial RoboticsDesign'],
            ['id' => 525, 'nama' => 'Teknik Kimia'],
            ['id' => 526, 'nama' => 'Teknik Fisika'],
            ['id' => 527, 'nama' => 'Teknik Perminyakan'],
            ['id' => 528, 'nama' => 'Rekayasa Infrastruktur Lingkungan'],
            ['id' => 529, 'nama' => 'Teknik Pesawat Udara'],
            ['id' => 530, 'nama' => 'Teknik Telekomunikasi dan Navigasi Udara'],
            ['id' => 531, 'nama' => 'Teknik Bangunan dan Landasan'],
            ['id' => 532, 'nama' => 'Teknik Listrik Bandara'],
            ['id' => 533, 'nama' => 'Teknik Ekonomi Konstruksi (Quantity Surveyor)'],
            ['id' => 534, 'nama' => 'Teknik Sistem Perkapalan'],
            ['id' => 535, 'nama' => 'Teknik Pengairan (Sumber Daya Air)'],
            ['id' => 536, 'nama' => 'Meteorologi Terapan'],
            ['id' => 537, 'nama' => 'Arsitektur Lanskap'],
            ['id' => 538, 'nama' => 'Teknik Konversi Energi'],
            ['id' => 539, 'nama' => 'Teknik Perpipaan'],
            ['id' => 540, 'nama' => 'MA - Bahasa'],
            ['id' => 541, 'nama' => 'SMA - Bahasa']
        ];

        foreach ($programstudi as $studi) {
            DB::table('program_studi')
                ->insert([
                    'id' => $studi['id'],
                    'nama' => $studi['nama']
                ]);
        }
    }
}
